services:
  webserver:
    image: nginx:alpine
    container_name: my-webserver
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins # Folder with the Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"    # Jenkins UI
      - "50000:50000"  # Jenkins agent
    volumes:
      - ./jenkins_home:/var/jenkins_home
      -  /var/run/docker.sock:/var/run/docker.sock  # allow Jenkins to run Docker commands
    restart: unless-stopped
